################################## BACKEND ##################################
### jekyll ###
gems:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

plugins:
  - jekyll-admin
  - jemoji

include: ["_pages"] #specifically include folders

markdown: kramdown

### web ###
jekyll-mentions:
base_url: https://github.com

url: https://x-ry.github.io
analytics-google: UA-97394091-1

permalink: /:title/ #Sets permalink for pages and posts

################################## SITE INFO ##################################
### surfaced ###
name: Ryan Newkirk
bio: CS/CE/Data Science Student, Civic Tech Enthusiast, Vedio Story Teller
title: Ryan Newkirk's Personal Website #(tab title)

### SEO ###
description: The personal site of Ryan Newkirk.
url: https://x-ry.github.io
twitter:
    username: RyanNewkirk1
#facebook: 
    username: http://www.facebook.com/ryan.newkirk.161
 #   app_id: 100006021049016
  #  publisher: 100006021049016
   # admin: 100006021049016
logo: assets/images/profiles/profile2.jpg
social:
    name: Ryan Newkirk
    links:
        - https://twitter.com/RyanNewkirk1
        - https://www.facebook.com/ryan.newkirk.161
       # - https://www.linkedin.com/in/justinwzig
        - https://x-ry.github.io/
        
       
        

################################## DESIGN & STRUCTURE ##################################
### design ###

animations: true

# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

### pages ###

# Page Control #
projects: true
about: true
blog: true
disqus: false

# uncomment for pagination
# paginate: 5
# paginate_path: "blog/:num/"

### posts ###
# Show In posts?
read-time: true
show-tags: true
related: true
show-author: true
post-advance-links: [blog] # Display links for next and previous posts for the specified categories

################################## AUTHOR INFO  ##################################
# Author Page Info #
authors:
    justinz:
        name: Ryan Newkirk
        bio: CS/CE Student, Econ Nerd, Web Designer, Adjective Enthusiast.
        external-image: false
        picture: assets/images/profiles/small-profile2.png
        hover-picture: assets/images/profiles/profile.jpg
        small-hover-picture: assets/images/profiles/small-profile.jpg
        twitter: RyanNewkirk1

# Profile Picture #
external-image: false
picture: assets/images/profiles/profile2.png
hover-picture: assets/images/profiles/profile.jpg

# Resume #
resume: true
resume-external: false
resume-url: assets/files/resume-noinfo.pdf

# Social Links 

twitter: RyanNewkirk1
facebook: /ryan.newkirk.161
#google: mygoogle
#instagram: justinwzig
# pinterest: mypinterest
#linkedin: justinwzig
#youtube: /channel/UCfRGThUf4GliN9K9MCg7QVg?view_as=subscriber
# spotify: myspotify
github: x-ry
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo

email: rnewkirk@cps.edu

################################## FRONT MATTER DEFAULTS ##################################
defaults:
  - scope:
      path: ""
    values:
      headerImage: false
      hidden: false
      image: assets/images/profiles/profile2.jpg
      star: false
      author: rnewkirk
      surfaceCategories: false
      surfaceTags: true
      showDate: true

theme: jekyll-theme-cayman
